### ISSUE TITLE
Please don't spam home directory

### ISSUE THREAD

**Issue by kseistrup** [Zaloog/kanban-python#1]
```sh
» kanban init
Created new pykanban.ini file @Home Directory
Use 'kanban init' to create kanban boards
» # WTF?
» cat ~/pykanban.ini
[settings.general]
Active_Board = 
Column_Min_Width = 35
Done_Limit = 10
Show_Footer = True

[settings.columns.visible]
Ready = True
Doing = True
Done = True
Deleted = False
Archived = False

[kanban_boards]
```

To place a configuration file as a visible file in the root of the user's home directory, is a no go.

Preferrably, use the directory `$XDG_CONFIG_HOME/kanban-python`, where `$XDG_CONFIG_HOME` defaults to `~/.config`.

If you do not like the XDG specification, at least put the config file in an invisible dot directory — e.g., `~/.kanban-python`.

To place a configuration file as a visible file in the root of the user's home directory, is a no go.

**Comment by Zaloog** [comment]
Hi @kseistrup,
I'll Stick With the .kanban-python directory i think.
Will Work on a fix tomorrow. Thanks for pointing Out.

Was already thinking about a folder solution, to also have all Board .json Files at that Central Location and not spread over multiple location.


Thanks for your Feedback :)

**Comment by Zaloog** [comment]
Hi @kseistrup,
deployed the new version, which now creates a `.kanban-python` folder and puts the pykanban.ini file inside that.
If you already created some boards/tasks, you can update to the latest version and then either:
- create the folder manually and put your existing `pykanban.ini` in it or
- use any `kanban` comman  to create the initial folder + a new configfile and then swap the new configfile with your already existing file 

Thanks again for pointing out.

This issue can be closed then right?


Have a nice day

**Comment by kseistrup** [comment]
Looks good, thanks! :pray:

**Comment by Zaloog** [comment]
@kseistrup FYI updated to XDG now

**Comment by kseistrup** [comment]
Sweet! :+1:
