### ISSUE TITLE
How to set terminal on MAC so left/right arrows work.

### ISSUE THREAD

**Issue by tperezskytap** [Zaloog/kanban-python#15]
On a MAC if I'm typing in a line of text and make a typo mistake, when I press the left-arrow to go back to the middle of the string I'm typing, it gives me the character sequence "^[[D" So it isn't interpreting the left arrow key correctly.

**Comment by Zaloog** [comment]
Hi @tperezskytap ,
Where do you run the application? ZSH?

**Comment by tperezskytap** [comment]
I am just using bash, don't have ZSH installed. But I can do that to try.

TP

Tony Perez
Cloud Solutions Architect
Skytap, Inc.
***@***.*** ***@***.***>* | M: 503-550-3361

**Comment by tperezskytap** [comment]
I did switch to zsh, but the same problem happens. When I hit the left
arrow I get the escape sequence but the left arrow doesn't happen.

TP

Tony Perez
Cloud Solutions Architect
Skytap, Inc.
***@***.*** ***@***.***>* | M: 503-550-3361

**Comment by Zaloog** [comment]
Hi @tperezskytap,
I updated the comment, after some quick googling, looks like you still responded to the old one.

It seems like theres the option to set that specific escape sequence to the `forward/backwards-character` command in your .zshrc


```shell
bindkey "^[[D" backward-character
bindkey "escape sequence for right arrow" forward-character
```

Maybe [this](https://stackoverflow.com/questions/12382499/looking-for-altleftarrowkey-solution-in-zsh) SO Post helps.

**Comment by Zaloog** [comment]
Hi @tperezskytap,
where you able to fix the issue?

**Comment by tperezskytap** [comment]
I have been playing with the bindkey parameters but have not solved them
yet.
Unless other users are reporting the same issue, don't worry. It is a minor
issue, and I'll keep playing with it.

TP

Tony Perez
Cloud Solutions Architect
Skytap, Inc.
***@***.*** ***@***.***>* | M: 503-550-3361

**Comment by Zaloog** [comment]
Sorry to hear its still present.
Ill close this issue then for now.
Feel free to respond if you`ve found a solution.

Best regards and a good start into the week :)
