### ISSUE TITLE
Feature Request: Kanban Boards at Repository Level

### ISSUE THREAD

**Issue by sweeneyal** [Zaloog/kanban-python#16]
I'd like to create individual Kanban boards to be stored at the repository level, w/o any global configuration beyond that. If possible, it would allow me to version control the Kanban board as part of my documentation, w/o the use of another external issue tracker. Additionally, I tend to work solo on my projects, often with no stakeholders to make an external issue tracker make sense, so having my issue tracker integrated into my development flow makes it a bit easier.

I understand you somewhat removed this as part of #2. If you could include this as part of command line arguments rather than system paths, I would greatly appreciate that.

**Comment by Zaloog** [comment]
Hi @sweeneyal,
Thanks for using kanban-python.
I am currently on vacation. I will look into the issue in more detail afterwards.

I also want to bring the project to a more modern structure using `uv` and utilize `click` for the command line arguments in the next months.

For your request, i was thinking about providing like a `--local` flag to tell kanban-python to look in the current working directory, or per default include a `local` board which checks if there is a pykanban.json file in the current working directory and if yes opens that one over the current active board in the config.

What do you think?

Best regards
Lars

**Comment by sweeneyal** [comment]
No worries, enjoy your vacation!

I think the second option would be best, but you could still add the --local flag to make it so that it only checks locally and returns an error if not found.

What would the board creation commands look like? Would they be something like `kanban init --local`, which would ideally force creation in the current working directory?

**Comment by Zaloog** [comment]
Either that, or it prompts and asks to create it local in CWD or not. But i think thats to much additional prompts, so i think the --local flag would be the approach id go for.

**Comment by sweeneyal** [comment]
Alright, sounds good. Thank you for listening, and I'm excited about the update!

**Comment by Zaloog** [comment]
@sweeneyal,

Updated the package. You can now create local boards by naming them `local` or with the shortcut flags.
Currently local boards are only accessible when in the same directory. 
I also improved the `--help` output and added optional path commands to report/scan functionality.

Please refer to the [Changelog](https://github.com/Zaloog/kanban-python/blob/main/CHANGELOG.md) for a detailed list.

Best regards
Lars

**Comment by sweeneyal** [comment]
Awesome, I'll test it out when I get a free moment. Thank you!

**Comment by sweeneyal** [comment]
Tested it, works great. I'm going to start using it for my projects. Thank you!
