### ISSUE TITLE
Feature request: automaticly add #todo

### ISSUE THREAD

**Issue by bjornasm** [Zaloog/kanban-python#4]
This looks great!

I use various vscode plugins that are able to record a todo list based on lines tagged with #todo in any file in your project. Would it be able to do any variant of this, maybe a variant of it - say adding a file if todo item automatically to the canban board (if using a different app to compile the todo list).

**Comment by Zaloog** [comment]
Hi @bjornasm,
Thank you.

I just installed a `#TODO` tracker for myself in vscode plugin 2 days ago :D . Havent thought about integrating it directly to the application.

To understand your Point better: Lets say we have some .py files in our current working directory, with several
 `# TODO : <Important thing to do>` lines.
We could parse those files and if we find a line with the structure like  `# TODO : <Important thing to do>`, we could generate a new task for each line like `[ID] (TODO) <Important thing to do>` and put them into the `Ready` column.

To prevent tasks being created again, after moving a specific task to `Doing/Done` column, we could make a quick comparison with existing tasks on the board that are tagged with `TODO` and make sure we dont add a duplicate.

What do you think?

**Comment by Zaloog** [comment]
Hey @bjornasm,

I have the scanning part ready, its pretty fast and checks > 1000 files/second:
![image](https://github.com/Zaloog/kanban-python/assets/57259263/1c5bc589-54bf-45d3-9440-eab6b493f5fa)

Still have to add the configurations for file types that should be checked (currently just  `[.py]`), and
which Patterns at linestart (currently `['# TODO', '#TODO']`).
And after that the task update to the `.json` file.

**Comment by Zaloog** [comment]
@bjornasm 
UPDATE: The scanning for '#TODO' or other patterns is implemented already on [this](https://github.com/Zaloog/kanban-python/tree/kanban-scan-function)  branch.

in short: using `kanban scan` scans all specific filetypes (configurable in config e.g. `.py`, `.md`) for specific patterns at linestart (also configurable in config e.g. `#TODO`, `#  BUG`),
![image](https://github.com/Zaloog/kanban-python/assets/57259263/ea654d2c-c829-4653-9d21-3276d8f0808b)


 it then will create tasks with the alphanum characters of the detected pattern (TODO, BUG) as tag, and the rest of the line as `title`. The Filepath where it was found will be added as description.
![image](https://github.com/Zaloog/kanban-python/assets/57259263/e85f5ec5-3a22-49bf-8a25-8ded890f5fec)


 I will Update the Docs tomorrow and make a new release 0.2.1.

After that I will work on the XDG path convention for config/data files, so some adjustments might be needed if you update to 0.2.2 then.

Have a nice evening

**Comment by Zaloog** [comment]
completed and released with version 0.2.1 :)
Thanks for the idea.

**Comment by bjornasm** [comment]
Thank you so much for the work on this @Zaloog - I am sorry for my delayed comments and for not following up! It looks like your implementation was just perfect, thank you!

**Comment by Zaloog** [comment]
Hey @bjornasm  no worries. 
Glad you like it.
Have a nice day
