### ISSUE TITLE
Feature Request - Add `show task` info option 

### ISSUE THREAD

**Issue by alex-rakowski** [Zaloog/kanban-python#5]
It would be great to add an option to dump task info in a pretty way, i.e. adding `show task` to `Whats up!?, how can I help you being productive today 🚀` default question. 

Currently, to get a task description you need to run `[2] 🔃 Update/Check Task` and step through the 4 questions including one which cannot be passed as empty (assign the task stage). 

Maybe something like:

```bash
# add to the prompt
[0] show task
# user inputs ID
Enter ID: 01
# outputs 
ID: 01
Title: Some Task
Tag: BUG
Task Description: Some longer text
```

Another nice option building off this would be able to show all tasks with a certain tag:

```bash
# add to the prompt
[0] show task/s
# user inputs ID
Enter ID or Tag: BUG

# outputs 
ID: 01
Title: Some Task
Tag: BUG
Task Description: Some longer text

ID: 04
Title: new Task
Tag: BUG
Task Description: Some longer text

ID: 05
Title: new new Task
Tag: BUG
Task Description: Some longer text
```

**Comment by Zaloog** [comment]
Hi @alex-rakowski,
This Sounds very useful, thanks for the detaled request. I will try adding Something Like that this week.
Gotta Check what the best way to visualize the Task is.
Either the Option you mentioned or in some Kind of Tablet maybe? Will have a Look at it and try both Methods With different amount of Tasks.

FYI. I removed the Default from the Status selection, so you could not accidently skip that Part, If you Just want to Change the Status, but rather be able to move to the Status section quickly.

Best regards :)

**Comment by Zaloog** [comment]
Hi @alex-rakowski ,
this new feature is now implemented:
![image](https://github.com/Zaloog/kanban-python/assets/57259263/a077492a-c16e-4337-bcc4-b50b303b0c93)

Its already pushed to main branch, I will release the new version 0.3.3 tomorrow after updating the Docs

Thanks again for your request and that you use kanban-python

Have a nice day

**Comment by Zaloog** [comment]
New version is live on PyPi and ready to be installed :)
