### ISSUE TITLE
Feature request: interpret ^D as quit

### ISSUE THREAD

**Issue by kseistrup** [Zaloog/kanban-python#9]
It seems `kanban` expects `^C` for quitting.

Usually on Linux, `^D` (`EOF`) is regarded as a signal to stop reading from standard input. When giving `kanban` a `^D` at the “Choose wisely” prompt, `kanban` dies with an `EOFError`.

I suggest treating `^C` and `^D` as synonyms.

(And perhaps allow `q` for quitting, too.)

**Comment by Zaloog** [comment]
So https://github.com/Zaloog/kanban-python/blob/2e652435ce618529b1201cec75ae98c1a8351e2d/src/kanban_python/app.py#L113-L114
This should just be a change to: 
```python 
except (KeyboardInterrupt, EOFError):
    utils.console.print(utils.get_motivational_quote())
```

To make it quitable with `^D` right?

q is not that simple, it needs more dependencies and some of those are platform specific.
Also I cant have it work on the overall app level, but just on specific inputs, cause it shouldnt abort the process when you enter a new task with `q` in its Title/Description/Tag or create a new board.

I think 2 options with `^C` and `^D` are enough for now.

**Comment by kseistrup** [comment]
Perfect! :+1:
